resolver: lts-15.13

packages:
- .

extra-deps:
  - ekg-0.4.0.15
  - ekg-core-0.1.1.7
  - ekg-json-0.1.0.6
  - net-mqtt-0.7.0.1
  - git: https://github.com/hstream-io/hesp.git
    commit: ac22865e0b4cc216941582b2da9f360918b98333
