loggerSetting:
  formatter: rich
  level: debug

# Whether to forward MQTT messages to TCP brokers.
crossForward: true

# Message processing functions.
# A message will go through these functions one by one.
sqlFiles: []

# Brokers. Each of them has following fields:
# - brokerName:  Name of the broker. It is a unique identifier of a broker.

# - brokerURI:   URI of the broker that the bridge will connect to.

# - connectType: Type of connection of this broker. It can be one of
#                MQTTConnection and TCPConnection.

# - brokerSubs:  Topic list which the broker subscribes. Only messages with
#                matched topic will be forwarded to this broker.

# - brokerFwds:  Topic list which the broker forwards. Only messages with
#                matched topic will be sent from this broker to the bridge.

# - brokerMount: Mountpoint of this broker. It will be added to the head of
#                topic of messages that the bridge receive from the broker.
#                This is mostly used for preventing message looping between brokers.
#                The bridge provides NO guarantee on loop-free property.

brokers:
-
  brokerName: broker1
  brokerMount: ''
  brokerURI: mqtt://test.mosquitto.org
  brokerFwds:
  - '#'
  brokerSubs:
  - '#'
  connectType: MQTTConnection

-
  brokerName: broker2
  brokerMount: ''
  brokerURI: mqtt://test.mosquitto.org
  brokerFwds:
  - '#'
  brokerSubs:
  - '#'
  connectType: MQTTConnection
